//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.OfficeStorage = new HashSet<OfficeStorage>();
        }
    
        public int IdComputer { get; set; }
        public int IdCPU { get; set; }
        public int IdMotherBoard { get; set; }
        public int IdRAM1 { get; set; }
        public Nullable<int> IdRAM2 { get; set; }
        public Nullable<int> IdRAM3 { get; set; }
        public Nullable<int> IdRAM4 { get; set; }
        public int IdGPU { get; set; }
        public int IdHDD { get; set; }
        public int IdCPUСooling { get; set; }
        public Nullable<int> IdSSD { get; set; }
        public int IdComputerCase { get; set; }
        public int IdPowerSupply { get; set; }
        public System.DateTime GuaranteeComputer { get; set; }
        public string SerialNumberComputer { get; set; }
    
        public virtual ComputerCase ComputerCase { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual CPUСooling CPUСooling { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual HDD HDD { get; set; }
        public virtual MotherBoard MotherBoard { get; set; }
        public virtual PowerSupply PowerSupply { get; set; }
        public virtual RAM1 RAM1 { get; set; }
        public virtual RAM2 RAM2 { get; set; }
        public virtual RAM3 RAM3 { get; set; }
        public virtual RAM4 RAM4 { get; set; }
        public virtual SSD SSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeStorage> OfficeStorage { get; set; }
    }
}
