//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<ComputerCase> ComputerCase { get; set; }
        public virtual DbSet<ComputerMouse> ComputerMouse { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<CPUСooling> CPUСooling { get; set; }
        public virtual DbSet<DigitalStorageCapacityHDD> DigitalStorageCapacityHDD { get; set; }
        public virtual DbSet<DigitalStorageCapacitySSD> DigitalStorageCapacitySSD { get; set; }
        public virtual DbSet<Garniture> Garniture { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<HDD> HDD { get; set; }
        public virtual DbSet<Headphones> Headphones { get; set; }
        public virtual DbSet<Keyboard> Keyboard { get; set; }
        public virtual DbSet<Microphone> Microphone { get; set; }
        public virtual DbSet<Monitor> Monitor { get; set; }
        public virtual DbSet<MotherBoard> MotherBoard { get; set; }
        public virtual DbSet<OfficeStorage> OfficeStorage { get; set; }
        public virtual DbSet<PowerSupply> PowerSupply { get; set; }
        public virtual DbSet<Printer> Printer { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<RAM1> RAM1 { get; set; }
        public virtual DbSet<RAM2> RAM2 { get; set; }
        public virtual DbSet<RAM3> RAM3 { get; set; }
        public virtual DbSet<RAM4> RAM4 { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Scanner> Scanner { get; set; }
        public virtual DbSet<SerialNumberRAM> SerialNumberRAM { get; set; }
        public virtual DbSet<SSD> SSD { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfCPUСooling> TypeOfCPUСooling { get; set; }
        public virtual DbSet<TypeOfRAM> TypeOfRAM { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Wattage> Wattage { get; set; }
        public virtual DbSet<WebCamera> WebCamera { get; set; }
    }
}
