//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalStorageCapacitySSD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DigitalStorageCapacitySSD()
        {
            this.SSD = new HashSet<SSD>();
        }
    
        public int IdDigitalStorageCapacitySSD { get; set; }
        public string NameDigitalStorageCapacitySSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSD> SSD { get; set; }
    }
}
