//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garniture()
        {
            this.OfficeStorage = new HashSet<OfficeStorage>();
        }
    
        public int IdGarniture { get; set; }
        public string NameGarniture { get; set; }
        public string SerialNumberGarniture { get; set; }
        public System.DateTime GaranteeGarniture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeStorage> OfficeStorage { get; set; }
    }
}
