//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDD()
        {
            this.Computer = new HashSet<Computer>();
        }
    
        public int IdHDD { get; set; }
        public string NameHDD { get; set; }
        public int IdDigitalStorageCapacityHDD { get; set; }
        public int QuantityHDD { get; set; }
        public string SerialNumberHDD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computer> Computer { get; set; }
        public virtual DigitalStorageCapacityHDD DigitalStorageCapacityHDD { get; set; }
    }
}
