//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomErshov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAudit
    {
        public int AuditId { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string Action { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
